## Five Things School Districts Can Do to Improve College Access for Low-income Students 

* Name: Shannon Coulter
* Organization/institution: San Diego County Office of Education
* Email: scoulter@sdcoe.net

* English

### Summary

This presentation shares the San Diego County Office of Education's work to improve college access for low-income students in San Diego.  SDCOE based the presentation on it change package **Make it Easier**. SDCOE designed this guide to support schools, school leaders, counselors, and others involved in improving college access and completion. The guide shares some “behavioral nudges” schools can make that will support students to continue along the pathway to enrolling in college. The guide offers:
- Guidance on how to support students with college application process, Free Application for Federal
 Student Aid (FAFSA) completion, and the college enrollment tasks students face in the summer
- Resources and tools that can help nudge students to follow through with their college enrollment
 intentions  

* The slides are available at:

  * https://cera2021fivethings.netlify.app

### Keywords

college access; change ideas; low-income